- name: Add the user cs
  ansible.builtin.user:
    name: cs
  register: cs_user
    
- name: Create run directory
  ansible.builtin.file:
    path: /var/run/cs
    state: directory
    mode: '0755'
    owner: cs
    group: cs

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: "{{ 'docker-compose.web.yml' if not cs_batch else 'docker-compose.batch.yml' }}"
    dest: /var/run/cs/docker-compose.yml
    owner: cs
    group: cs
    mode: '0644'

- name: Copy .env
  ansible.builtin.copy:
    dest: /var/run/cs/.env
    owner: cs
    group: cs
    mode: '0640'
    content: |
      UID={{ cs_user.uid }}
      GID={{ cs_user.uid }}
      ENV={{ cs_env }}
      DEBUG={{ cs_debug }}
      DOMAIN={{ cs_domain }}
      API_EXPOSE_PORT={{ cs_api_expose_port }}
      SIGN_EXPOSE_PORT={{ cs_sign_expose_port }}
      WS_EXPOSE_PORT={{ cs_ws_expose_port }}
      ADMIN_EXPOSE_PORT={{ cs_admin_expose_port }}      
      SECRET_KEY={{ cs_secret_key }}
      EMAIL_URL={{ cs_email_url }}
      SENDER_EMAIL={{ cs_sender_email }}
      DATABASE_URL={{ cs_database_url }}
      CACHE_URL={{ cs_cache_url }}
      BROKER_URL={{ cs_broker_url }}
      REDIS_CHANNEL_URL={{ cs_redis_channel_url }}
      ES_URL={{ cs_es_url }}
      AWS_ACCESS_KEY_ID={{ cs_aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY={{ cs_aws_secret_access_key }}
      AWS_S3_ENDPOINT_URL={{ cs_aws_s3_endpoint_url }}
      AWS_S3_CUSTOM_DOMAIN={{ cs_aws_s3_custom_domain }}
      AWS_S3_ADRESSING_STYLE={{ cs_aws_s3_adressing_style }}
      AWS_S3_SIGNATURE_VERSION={{ cs_aws_s3_signature_version }}
      MAPQUEST_API_KEY={{ cs_aws_mapquest_api_key }}
      GOOGLE_API_KEY={{ cs_google_api_key }}
      GOOGLE_OAUTH2_KEY={{ cs_google_oauth2_key }}
      GOOGLE_OAUTH2_SECRET={{ cs_google_oauth2_secret }}
      FACEBOOK_OAUTH2_KEY={{ cs_facebook_oauth2_key }}
      FACEBOOK_OAUTH2_SECRET={{ cs_facebook_oauth2_secret }}
      FCM_API_KEY={{ cs_fcm_api_key }}
      APPLE_ID_CLIENT={{ cs_apple_id_client }}
      APPLE_ID_TEAM={{ cs_apple_id_team }}
      APPLE_ID_KEY={{ cs_apple_id_key }}
      APPLE_ID_SECRET={{ cs_apple_id_secret }}

- community.docker.docker_compose:
    project_src: /var/run/cs
    state: absent

- community.docker.docker_compose:
    project_src: /var/run/cs
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.api.cs_api_1.state.running"
      - "output.services.admin.cs_admin_1.state.running"
      - "output.services.ws.cs_ws_1.state.running"
      - "output.services.sign.cs_sign_1.state.running"
