---
roles:
  - name: geerlingguy.redis
  - name: geerlingguy.postgresql
  - name: geerlingguy.java
  - name: geerlingguy.elasticsearch
  - name: geerlingguy.rabbitmq
  - name: geerlingguy.gitlab
  - name: geerlingguy.nginx
  - name: geerlingguy.certbot
