---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ mailserver_hostname.split('.')[0] }}"

- name: Set FQDN in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^\s*{{ ansible_default_ipv4.address | default("127.0.1.1") }}'
    line: "{{ ansible_default_ipv4.address | default('127.0.1.1') }} {{ mailserver_hostname }} {{ mailserver_hostname.split('.')[0] }}"
    state: present

- name: Ensure localhost entry exists
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^\s*127\.0\.0\.1'
    line: "127.0.0.1 localhost.localdomain localhost"
    state: present
