---
- name: Install mail server packages
  ansible.builtin.apt:
    name:
      - postfix
      - postfix-pgsql
      - postfix-pcre
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-pop3d
      - dovecot-pgsql
      - dovecot-sieve
      - dovecot-managesieved
      - opendkim
      - opendkim-tools
      - opendmarc
      - spamassassin
      - spamc
      - postgresql
      - postgresql-contrib
      - certbot
      - python3-certbot-dns-ovh
      - nginx
      - python3-psycopg2
      - python3-ovh
      - procmail
    state: present
    update_cache: true
