---
private_network: "192.168.0.64/27"
admin_network: "192.168.1.64/27"

gitlab_domain: gitlab.zozoh.fr
gitlab_external_url: "https://{{ gitlab_domain }}/"
gitlab_create_self_signed_cert: true
gitlab_self_signed_cert_subj: "/C=FR/ST=Ile-et-Vilaine/L=Rennes/O=Zozoh/CN={{ gitlab_domain }}"
gitlab_registry_enable: true
gitlab_registry_external_url: "https://registry.zozoh.fr"
gitlab_pages_external_url: "http://pages.zozoh.fr"
gitlab_redirect_http_to_https: false
gitlab_nginx_listen_https: false
gitlab_nginx_listen_port: 80
gitlab_extra_settings:
  - nginx:
      - key: "listen_address"
        value: "0.0.0.0"
  - gitlab_rails:
      - key: "gitlab_shell_ssh_port"
        value: "2222"
  - registry_nginx:
      - key: "redirect_http_to_https"
        value: false
      - key: "listen_https"
        value: false
      - key: "listen_address"
        value: "0.0.0.0"
      - key: "listen_port"
        value: "5678"
  - registry:
      - key: "database"
        type: plain
        value: "{ 'enabled' => true, 'host' => '/var/opt/gitlab/postgresql', 'port' => 5432, 'user' => 'registry', 'dbname' => 'registry', 'sslmode' => 'prefer' }"
group_hosts:
  gitlab.zozoh.fr: 192.168.0.225
  registry.zozoh.fr: 192.168.0.225
  gitlab.ovh.zozoh.fr: 192.168.0.66
  gitlab-runner1.ovh.zozoh.fr: 192.168.0.67
        

gitlab_runner_url: "{{ gitlab_external_url }}"

