---
- name: Restart coolify proxy
  become: yes
  community.docker.docker_compose_v2:
    project_src: "{{ coolify_proxy_dir }}"
    state: present
    recreate: always

- name: Restart dnsmasq
  become: yes
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart docker
  become: yes
  ansible.builtin.service:
    name: docker
    state: restarted
