---
- name: Restart dnsmasq
  become: yes
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart docker
  become: yes
  ansible.builtin.service:
    name: docker
    state: restarted
