---
version: '3'

services:
  batch:
    restart: always
    image: registry.zozoh.fr/cathosphere_batch:latest
    user: "${UID}:${GID}"
    env_file:
      - .env

  mjml:
    restart: always
    image: liminspace/mjml-tcpserver:latest
    environment:
      MJML_ARGS: "--mjml.minify=true --mjml.validationLevel=soft"
