---
- name: Reload nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart docker compose
  become: yes
  community.docker.docker_compose_v2:
    project_src: "{{ vaultwarden_data_dir }}"
    state: present
