---
- name: Install gpg
  apt:
    name: gpg
    state: present    

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest

- name: Install docker-compose
  block:
    - name: Get binary
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/bin/docker-compose
        checksum: "{{ docker_compose_checksum }}"
        mode: "0755"

- name: Log into Zozoh registry and force re-authorization
  docker_login:
    registry: registry.zozoh.fr
    username: "{{ registry_zozoh_username }}"
    password: "{{ registry_zozoh_password }}"
    reauthorize: yes

- name: Install pip
  apt:
    name: python3-pip
    state: latest
    
- name: Install Docker Module for Python
  pip:
    name: docker
