---
galaxy_info:
  author: zozoh
  description: Complete mail server with Postfix, Dovecot, OpenDKIM, OpenDMARC, SpamAssassin
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - mail
    - postfix
    - dovecot
    - dkim
    - dmarc
    - spamassassin

dependencies: []

collections:
  - community.postgresql
