---
- hosts: broker
  become: yes

  vars:
    redis_bind_interface: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(private_network) | first }}"
    redis_requirepass: "{{ redis_broker_password }}"

    sshd_listen: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(admin_network) | first }}"

  roles:
    - common
    - geerlingguy.redis
    - rabbitmq
