---
- hosts: media

  become: yes
  
  vars:
    sshd_listen: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(admin_network) | first }}"

    minio_console_listen_address: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(private_network) | first }}"
    minio_listen_address: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(private_network) | first }}"
    minio_browser_redirect_url: http://minio.cathosphere.co
    
  roles:
    - common
    - minio

  
