---
- hosts: web

  become: yes
  
  vars:
    sshd_listen: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(admin_network) | first }}"
    install_docker: true
    
  roles:
    - common
    - cs
