---
role_coolify_played: false

# Official Coolify installer
coolify_install_url: "https://cdn.coollabs.io/coolify/install.sh"

# Path created by the Coolify installer (guards the idempotent install step)
coolify_source_compose: /data/coolify/source/docker-compose.yml
